# -*- coding: utf-8 -*-
"""TallerK4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158YaACMXufqpTFYR0w0h6zSQef51Cw8o
"""

import pandas as pd
import requests

#Leer el archivo Json
url = "https://raw.githubusercontent.com/CesarMCuellarCha/archivosCSV/refs/heads/main/deportistas.json"
respuesta = requests.get(url)
datosDeportistas = respuesta.json()
df = pd.DataFrame(datosDeportistas)

#Filtrar deportistas de género Femenino y guardar
mujeres = df[df["sexo"] == "Femenino"]
mujeres.to_json("deportistasMujeres.json", orient="records", force_ascii=False, indent=4)

#Filtrar ciclistas de ruta de 28 a 35 años y guardar
ciclismoRuta = df[(df["deporte"] == "Ciclismo de ruta") & (df["edad"].between(28, 35))]
ciclismoRuta.to_json("deportistasCiclismoRuta.json", orient="records", force_ascii=False, indent=4)

#Calcular promedio de edad de mujeres que practican baloncesto
mujeresBaloncesto = df[(df["sexo"] == "Femenino") & (df["deporte"] == "Baloncesto")]
promedioEdad = mujeresBaloncesto["edad"].mean()
print(f"Promedio de edad de mujeres en baloncesto: {promedioEdad:.2f} años")

#Mostrar datos del deportista masculino de mayor edad
hombres = df[df["sexo"] == "Masculino"]
deportistaMayorEdad = hombres.loc[hombres["edad"].idxmax()]
print("\nDeportista masculino de mayor edad:")
print(deportistaMayorEdad)

#Filtrar deportistas con estatura > 1.85 y guardar
estaturaMayor = df[df["estatura"] > 1.85]
estaturaMayor.to_json("deportistasEstaturaMayor_1.85.json", orient="records", force_ascii=False, indent=4)

print("\nTodos los archivos han sido creados exitosamente.")