# -*- coding: utf-8 -*-
"""TallerK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158YaACMXufqpTFYR0w0h6zSQef51Cw8o
"""

import csv

# 1. Crear el archivo inventario.csv
datos_productos = [
    ["codigo", "nombre", "precio", "cantidad"],
    ["P01", "Teclado", 50000, 10],
    ["P02", "Mouse", 30000, 15],
    ["P03", "Monitor", 200000, 5],
    ["P04", "Impresora", 150000, 3],
    ["P05", "Laptop", 800000, 2]
]

with open("inventario.csv", "w", newline="", encoding="utf-8") as archivo:
    escritor = csv.writer(archivo)
    escritor.writerows(datos_productos)

print("Lista de productos:")
with open("inventario.csv", "r", encoding="utf-8") as archivo:
    lector = csv.reader(archivo)
    encabezado = next(lector)
    for fila in lector:
        print(fila)

valor_total = 0
with open("inventario.csv", "r", encoding="utf-8") as archivo:
    lector = csv.DictReader(archivo)
    for fila in lector:
        precio = int(fila["precio"])
        cantidad = int(fila["cantidad"])
        valor_total += precio * cantidad

print(f"\nValor total del inventario: ${valor_total:,}")