# -*- coding: utf-8 -*-
"""TallerK2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158YaACMXufqpTFYR0w0h6zSQef51Cw8o
"""

import pandas as pd

# Leer el archivo inventario.csv con Pandas
df = pd.read_csv("inventario.csv")

# Mostrar el producto más costoso y el de mayor cantidad
# Producto más costoso
producto_mas_costoso = df.loc[df["precio"].idxmax()]
print("Producto más costoso:")
print(producto_mas_costoso)

# Producto con mayor cantidad
producto_mayor_cantidad = df.loc[df["cantidad"].idxmax()]
print("\nProducto con mayor cantidad:")
print(producto_mayor_cantidad)

df["valor_total"] = df["precio"] * df["cantidad"]

# Guardar el archivo actualizado
df.to_csv("inventario_actualizado.csv", index=False, encoding="utf-8")
print("\nArchivo inventario_actualizado.csv guardado exitosamente.")