# -*- coding: utf-8 -*-
"""TallerK3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158YaACMXufqpTFYR0w0h6zSQef51Cw8o
"""

import json
import pandas as pd

#Crear el archivo elecciones.json con datos de 10 departamentos
datosElecciones = [
    {"Departamento": "Cauca", "CantidadVotantesHombres": 1200, "CantidadVotantesMujeres": 2400},
    {"Departamento": "Huila", "CantidadVotantesHombres": 4900, "CantidadVotantesMujeres": 3950},
    {"Departamento": "Antioquia", "CantidadVotantesHombres": 15000, "CantidadVotantesMujeres": 18000},
    {"Departamento": "Cundinamarca", "CantidadVotantesHombres": 20000, "CantidadVotantesMujeres": 22000},
    {"Departamento": "Valle del Cauca", "CantidadVotantesHombres": 12000, "CantidadVotantesMujeres": 13500},
    {"Departamento": "Santander", "CantidadVotantesHombres": 8000, "CantidadVotantesMujeres": 7500},
    {"Departamento": "Bolivar", "CantidadVotantesHombres": 6000, "CantidadVotantesMujeres": 6800},
    {"Departamento": "Cordoba", "CantidadVotantesHombres": 5000, "CantidadVotantesMujeres": 5200},
    {"Departamento": "Nariño", "CantidadVotantesHombres": 4500, "CantidadVotantesMujeres": 4800},
    {"Departamento": "Tolima", "CantidadVotantesHombres": 7000, "CantidadVotantesMujeres": 6500}
]

with open("elecciones.json", "w", encoding="utf-8") as archivo:
    json.dump(datosElecciones, archivo, ensure_ascii=False, indent=4)

#Leer el archivo y procesar todos los datos con Pandas
df = pd.read_json("elecciones.json")

#Filtrar departamentos donde hay mayoría de mujeres
mayoriaMujeres = df[df["CantidadVotantesMujeres"] > df["CantidadVotantesHombres"]].copy()

#Calcular total de votantes y porcentajes
mayoriaMujeres["TotalVotantes"] = mayoriaMujeres["CantidadVotantesHombres"] + mayoriaMujeres["CantidadVotantesMujeres"]
mayoriaMujeres["Porcentaje_Hombres"] = round(mayoriaMujeres["CantidadVotantesHombres"] / mayoriaMujeres["TotalVotantes"], 2)
mayoriaMujeres["Porcentaje_Mujeres"] = round(mayoriaMujeres["CantidadVotantesMujeres"] / mayoriaMujeres["TotalVotantes"], 2)

#Guardar el resultado en mayoría_mujeres_departamento.json
mayoriaMujeres.to_json("mayoriaMujeresDepartamento.json", orient="records", force_ascii=False, indent=4)

print("Archivos elecciones.json y mayoríaMujeresDepartamento.json creados exitosamente.")